apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      securityContext:
        fsGroup: 1000
      serviceAccountName: vault
      containers:
        - name: vault
          image: "hashicorp/vault"
          command: ["vault"]
          args: ["server", "-config=/vault/config/vault.hcl"]
          ports:
            - containerPort: 8200
              name: http
            - containerPort: 8201
              name: internal
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
            runAsGroup: 1000
            capabilities:
              add: ["IPC_LOCK"]
          env:
            - name: VAULT_ADDR
              value: "http://127.0.0.1:8200"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: vault-config
              mountPath: /vault/config
            - name: vault-data
              mountPath: /vault/file
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: vault-config
          configMap:
            name: vault-config
        - name: vault-data
          persistentVolumeClaim:
            claimName: vault-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
spec:
  selector:
    app: vault
  ports:
    - name: http
      port: 8200
      targetPort: 8200
    - name: internal
      port: 8201
      targetPort: 8201
  type: ClusterIP
