apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: vault-gateway
  namespace: vault
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "vault.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vault
  namespace: vault
spec:
  hosts:
    - "vault.com"
  gateways:
    - vault-gateway
  http:
    - route:
        - destination:
            host: vault.vault.svc.cluster.local
            port:
              number: 8200
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: vault
  namespace: vault
spec:
  host: vault.vault.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
