apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    type: nfs
    app: postgres
    vol: pv-nfs
spec:
  storageClassName: "manual"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/snap/microk8s/common/nfs-storage
