apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: database
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432    # internal cluster port
      targetPort: 5432  # container port
      nodePort: 32432
  selector:
    app: postgres