apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: development-env-gateway
  namespace: development-env
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*" # Or your specific domain, e.g., "your-app.example.com"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "your-tls-secret" # Replace with your TLS secret name
    hosts:
    - "*" # Or your specific domain