apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-volume
  labels:
    type: nfs
    app: elasticsearch
    vol: elasticsearch-pv-nfs
spec:
  storageClassName: "nfs"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/snap/microk8s/common/nfs-storage
