apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-volume-claim
  namespace: logging
  labels:
    app: elasticsearch
    vol: elasticsearch-pvc-nfs
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
